-- Create experiences table for admin-managed seasonal & cultural experience videos

CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NULL,
  video_url TEXT NULL,
  thumbnail_url TEXT NULL,
  created_by UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS update_experiences_updated_at ON public.experiences;
CREATE TRIGGER update_experiences_updated_at
BEFORE UPDATE ON public.experiences
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read experiences" ON public.experiences;
CREATE POLICY "Admins can read experiences" ON public.experiences
FOR SELECT
USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can insert experiences" ON public.experiences;
CREATE POLICY "Admins can insert experiences" ON public.experiences
FOR INSERT
WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can update experiences" ON public.experiences;
CREATE POLICY "Admins can update experiences" ON public.experiences
FOR UPDATE
USING (is_admin(auth.uid()))
WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can delete experiences" ON public.experiences;
CREATE POLICY "Admins can delete experiences" ON public.experiences
FOR DELETE
USING (is_admin(auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.experiences TO authenticated;
