-- Create moods table for admin-managed mood videos

CREATE TABLE IF NOT EXISTS public.moods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NULL,
  video_url TEXT NOT NULL,
  thumbnail_url TEXT NOT NULL,
  created_by UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS update_moods_updated_at ON public.moods;
CREATE TRIGGER update_moods_updated_at
BEFORE UPDATE ON public.moods
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.moods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read moods" ON public.moods;
CREATE POLICY "Admins can read moods" ON public.moods
FOR SELECT
USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can insert moods" ON public.moods;
CREATE POLICY "Admins can insert moods" ON public.moods
FOR INSERT
WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can update moods" ON public.moods;
CREATE POLICY "Admins can update moods" ON public.moods
FOR UPDATE
USING (is_admin(auth.uid()))
WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can delete moods" ON public.moods;
CREATE POLICY "Admins can delete moods" ON public.moods
FOR DELETE
USING (is_admin(auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.moods TO authenticated;
